workflows:
  ios-simulator-workflow:
    name: iOS Simulator Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS for Simulator
        script: flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/**/*.app
